name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  pull-requests: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Perform compilation
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            src/dminca/dminca.tex
            src/kubecon/main.tex
      - name: Add only PDFs to git
        run: |
          git add -f *.pdf
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: "chore(ci): update PDFs"
            branch: update-dependencies

